# boot_harnesses
- BOOT_POST_TRAP
- BOOT_EARLYBOOT
- BOOT_DOINITCALLS_PCI
- BOOT_DOINITCALLS_VIRTIO
- BOOT_DOINITCALLS_ACPI
- BOOT_FULL_BOOT
- BOOT_REST_INIT
- BOOT_VIRTIO_BLK_PROBE
- BOOT_START_KERNEL
- BOOT_DO_BASIC
- BOOT_ACPI_EARLY_INIT
# initcall_harnesses
- DOINITCALLS_LEVEL_3
- DOINITCALLS_LEVEL_4
- DOINITCALLS_LEVEL_5
- DOINITCALLS_LEVEL_6
- DOINITCALLS_LEVEL_7
# bph_harnesses
- BPH_ACPI_INIT
- BPH_VP_MODERN_PROBE
- BPH_VIRTIO_CONSOLE_INIT
- BPH_P9_VIRTIO_PROBE
- BPH_PCI_SUBSYS_INIT
- BPH_HANDLE_CONTROL_MESSAGE
- BPH_VIRTIO_PCI_PROBE
- BPH_PCIBIOS_FIXUP_IRQS
# user_harnesses
- US_DHCP
- US_RESUME_SUSPEND
