- hosts: all
  vars:
    install_root: "{{ playbook_dir | dirname if ansible_connection == 'local' else ansible_env.HOME + '/ccc'}}"

  roles:
    - role: intellabs.kafl.fuzzer
      tags:
        - fuzzer
      vars:
        fuzzer_revision: kafl_tdx
        qemu_revision: kafl_stable_tdx
        libxdc_revision: kafl_stable_tdx
        kernel_deb_urls:
          - https://github.com/IntelLabs/kafl.linux/releases/download/kafl%2Fsdv-5.6-rc1/linux-image-5.6.0-rc1-tdfl+_5.6.0-rc1-tdfl+-7_amd64.deb
        kernel_grub_default: 'gnulinux-advanced-49764e08-5aba-4fc8-ab39-e9d3b268e429>gnulinux-5.6.0-rc1-sdv-kafl-tdfl+-advanced-49764e08-5aba-4fc8-ab39-e9d3b268e429'
        # install kafl in its own subdir
        # can't reuse install_root because of jinja templating recursion issue
        kafl_install_root: "{{ playbook_dir | dirname if ansible_connection == 'local' else ansible_env.HOME + '/ccc'}}/kafl"

    - role: tdvf
      tags:
        - tdvf
    - role: guest
      tags:
        - guest
    - role: smatch
      tags:
        - smatch
    - role: nyx_packer
      tags:
        - nyx_packer

  post_tasks:
    - name: Install env file
      template:
        src: env.j2
        dest: "{{ install_root }}/.env"
