- hosts: all
  vars_files:
    - vars.yml

  roles:
    - role: wenzel.kafl.kafl
      tags:
        - kafl
      vars:
        kafl_revision: kafl_tdx
        qemu_revision: kafl_stable_tdx
        libxdc_revision: kafl_stable_tdx

    - role: tdvf
      tags:
        - tdvf
    - role: guest
      tags:
        - guest
    - role: smatch
      tags:
        - smatch
    - role: nyx_packer
      tags:
        - nyx_packer

  post_tasks:
    - name: Install env file
      template:
        src: env.j2
        dest: "{{ install_root }}/.env"
