- hosts: all
  vars:
    install_root: "{{ playbook_dir | dirname if ansible_connection == 'local' else ansible_env.HOME + '/ccc'}}"

  roles:
    - role: wenzel.kafl.kafl
      tags:
        - kafl
      vars:
        kafl_revision: kafl_tdx
        qemu_revision: kafl_stable_tdx
        libxdc_revision: kafl_stable_tdx
        # install kafl in its own subdir
        # can't reuse install_root because of jinja templating recursion issue
        kafl_install_root: "{{ playbook_dir | dirname if ansible_connection == 'local' else ansible_env.HOME + '/ccc'}}/kafl"

    - role: tdvf
      tags:
        - tdvf
    - role: guest
      tags:
        - guest
    - role: smatch
      tags:
        - smatch
    - role: nyx_packer
      tags:
        - nyx_packer

  post_tasks:
    - name: Install env file
      template:
        src: env.j2
        dest: "{{ install_root }}/.env"
