- name: Install TDVF build dependencies
  ansible.builtin.package:
    name:
      - nasm
      - iasl
      - uuid-dev
      - python
    state: present
  become: true

- name: Clone TDVF repo
  ansible.builtin.git:
    repo: "{{ tdvf_url }}"
    dest: "{{ tdvf_root }}"
    version: "{{ tdvf_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: true

- name: Build BaseTools
  ansible.builtin.make:
    chdir: "{{ tdvf_root }}/BaseTools"
    params:
      --jobs: "{{ ansible_processor_nproc }}"

- name: Build TDVF
  ansible.builtin.shell: >
    source edksetup.sh --reconfig &&
    build -n $(nproc) -p OvmfPkg/OvmfPkgX64.dsc -t GCC5 -a X64 -D TDX_EMULATION_ENABLE=FALSE -D DEBUG_ON_SERIAL_PORT=TRUE
  args:
    executable: /bin/bash
    chdir: "{{ tdvf_root }}"
  changed_when: false
