- name: Install linux kernel build dependencies
  package:
    name:
      - libelf-dev
      - flex
      - bison
    state: present
  become: yes

- name: Clone linux-guest repo
  git:
    repo: "{{ guest_url }}"
    dest: "{{ guest_root }}"
    version: "{{ guest_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: yes

- name: Copy BKC TDX guest kernel config
  copy:
    src: "{{ playbook_dir }}/bkc/kafl/linux_kernel_tdx_guest.config"
    dest: "{{ guest_root }}/.config"
    remote_src: yes

- name: Enable Virtio harness
  command: "{{ item }}"
  args:
    chdir: "{{ guest_root }}"
  with_items:
    - ./scripts/config -e CONFIG_TDX_FUZZ_KAFL
    - ./scripts/config -e CONFIG_TDX_FUZZ_HARNESS_DOINITCALLS_VIRTIO

- name: Build TDX guest kernel
  make:
    chdir: "{{ guest_root }}"
    params:
      --jobs: "{{ ansible_processor_nproc }}"
