name: Deployment

# trigger build on every pull request activity against master branch
on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Setup ansible
        run: |
          apt update && apt install -y make python3-venv
          make venv

      # skip tags related to non-existent hardware/configuration in the CI runner environment
      # shallow clone for CI
      - name: Test deployment
        run: make deploy_ci
